### ISSUE TITLE
Follow execs with allocation profiling

### ISSUE THREAD

**Issue by r1viollet** [DataDog/ddprof#182]
# Description

When a program executes another program, we do not follow with the allocation profiling.

# Motivation 

Today we need to be especially careful when launching applications through bash scripts (as we will only profile the bash script when wrapping)

# Design

We currently register watchers during startup.
An exec can happen at any time in the program's lifetime. 

## Possible solution

Keep our IPC mechanism open. Send a message when we want to register a new PID, listen on a new ring buffer.

**Comment by nsavoire** [comment]
Implemented in https://github.com/DataDog/ddprof/pull/342
