### ISSUE TITLE
Configurable sampling frequency

### ISSUE THREAD

**Issue by NHDaly** [DataDog/ddprof#248]
From what I understand from @aristotelhs, ddprof has a fixed sampling frequency of 100hz.

This is higher than we wanted/expected, and we are a tad concerned about leaving this on all continuously in prod without impacting performance. (Additionally, setting a lower frequency should save storage costs in datadog! 😊)

Can we have the ability to configure this?
Thank you!

**Comment by r1viollet** [comment]
Yes, this is indeed supported. Here is an example:

```
./ddprof --show_config yes -e sCPU,period=10
```

I will add more documentation on the grammar in future releases. We are still working on the  configuration mechanisms.

**Comment by aristotelhs** [comment]
Thank you. This is indeed helpful. We did not find documentation about the rest of the options and how they could be used to fine tune, looking forward to the additions.

**Comment by NHDaly** [comment]
Thank you;

**Comment by r1viollet** [comment]
This was documented as part of the PR #277 , the watcher configurations will change with the addition of live heap tracking.

**Comment by NHDaly** [comment]
FWIW @r1viollet: I still found it hard to tell from the current documentation page how to change the sampling frequency:
https://github.com/DataDog/ddprof/blob/main/docs/Commands.md

Maybe you could include your example, `-e sCPU,period=10`, in the documentation under the `-e` command?
