### ISSUE TITLE
maintain a static URL pointing to the latest version

### ISSUE THREAD

**Issue by mingmxu** [DataDog/ddprof#368]
Currently the URL of the latest release package keeps changing, which makes it hard to catch up with the latest version. It would be helpful to maintain a static link similar as https://github.com/DataDog/dd-trace-java. 

It has a short URL https://dtdg.co/latest-java-tracer, which is 302-redirected to https://github.com/DataDog/dd-trace-java/releases/download/download-latest/dd-java-agent.jar, always get the latest binary when rebuilding an image.

**Comment by nsavoire** [comment]
Thanks for the suggestion !
https://github.com/DataDog/ddprof/releases/latest/download/ddprof-amd64-linux.tar.xz now points to the latest stable ddprof release.
Similarly https://github.com/DataDog/ddprof/releases/download/latest-rc/ddprof-amd64-linux.tar.xz points on the latest release candidate.

**Comment by mingmxu** [comment]
thank you for working on it, verified the links work thus I'm closing the issue.
